name: CI/CD for Monitoring Solutions

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ['process-monitor', 'port-checker', 'ssl-checker']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Bash
      run: echo "SHELL=/bin/bash" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        # Общие зависимости
        sudo apt-get install -y shellcheck
        # Зависимости для конкретных компонентов
        if [ "${{ matrix.component }}" = "ssl-checker" ]; then
          sudo apt-get install -y openssl
        fi
        if [ "${{ matrix.component }}" = "process-monitor" ]; then
          sudo apt-get install -y curl procps
        fi
        if [ "${{ matrix.component }}" = "port-checker" ]; then
          sudo apt-get install -y netcat-openbsd
        fi

    - name: Lint check for ${{ matrix.component }}
      run: |
        cd ${{ matrix.component }}/src
        if ls *.sh 1> /dev/null 2>&1; then
          shellcheck *.sh || echo "ShellCheck issues found but not failing build"
        else
          echo "No shell scripts found for linting"
        fi

    - name: Test ${{ matrix.component }}
      run: |
        cd ${{ matrix.component }}
        if [ -f "scripts/test-${{ matrix.component }}.sh" ]; then
          chmod +x scripts/test-*.sh
          ./scripts/test-${{ matrix.component }}.sh
        else
          echo "No test script found for ${{ matrix.component }}"
        fi

    - name: Validate configuration examples
      run: |
        cd ${{ matrix.component }}
        if [ -d "examples" ]; then
          cd examples
          for conf_file in *.conf*; do
            if [ -f "$conf_file" ]; then
              echo "Validating $conf_file"
              if [ -f "../scripts/validate-config.sh" ]; then
                ../scripts/validate-config.sh "$conf_file"
              fi
            fi
          done
        fi

  docker-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: ./docker
        push: false
        tags: monitoring-solutions:latest

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create release archive
      run: |
        mkdir release
        cp -r process-monitor release/
        cp -r port-checker release/
        cp -r ssl-checker release/
        cp -r docker release/
        cp -r scripts release/
        cp -r docs release/
        cp -r examples release/
        cp LICENSE release/
        cp README.md release/
        cp CHANGELOG.md release/
        
        tar -czf monitoring-solutions-${GITHUB_REF#refs/tags/}.tar.gz -C release .
        
    - name: Upload release asset
      uses: actions/upload-artifact@v3
      with:
        name: monitoring-solutions-package
        path: monitoring-solutions-${GITHUB_REF#refs/tags/}.tar.gz